### ISSUE TITLE
Add Discards

### ISSUE THREAD

**Issue by Craig44** [NIWAFisheriesModelling/CASAL2#123]
Add discard process/observation

**Comment by SamikDatta** [comment]
Hi @Craig44 - I'm incorporating the additional files you added (ProcessDiscardsByAge.cpp and .h in Observations/Age), plus the files Ian has written (MortalityInstantaneousRetained.cpp and .h in Processes/Age). One thing I noticed when I pulled your changes - your branch is older, and still has files Scott deleted from the entire history (removing real data from testcases). You need to do a clean pull from the master repo before making further changes, otherwise any pull requests you make will contain the old files - I just noticed because I have them in my branch after pulling your changes.

**Comment by Craig44** [comment]
Lame... I think I have cleaned it up can you check @SamikDatta that there is no real data in my fork. In terms of merging the changes, it might be best if you start your own branch and copy the relevent info as not to contaminate the master

**Comment by SamikDatta** [comment]
Yep, that's what I'm planning. I'm just trying to get it to compile at the mo, once I do I'll manually take what I need.

@Craig44 - can you just check about the changes I should take from you from your branch:

https://github.com/NIWAFisheriesModelling/CASAL2/compare/master...Craig44:Discards

There are a lot of files (e.g. Reports/Age/AgeLength.cpp) where there are the following changes:
-  run_mode_    = (RunMode::Type)(RunMode::kBasic | RunMode::kProjection);
-  model_state_ = State::kFinalise;
+  run_mode_    = (RunMode::Type)(RunMode::kBasic | RunMode::kProjection | RunMode::kSimulation| RunMode::kEstimation | RunMode::kProfiling);
+  model_state_ = (State::Type)(State::kIterationComplete);

Are these intentional? They're not in the current master files, so I'm unsure if you did these manually or I should ignore them.

**Comment by Craig44** [comment]
Ignore all of that, I don't know what I have gone and done, apoligies. If you have all the relevent discard info I will delete my forked branch.

**Comment by SamikDatta** [comment]
OK, I've pulled what I thought were the relevant files:

- CASAL2/source/Observations/Age/ProcessDiscardsByAge.cpp (and .h) - new files
- CASAL2/source/Observations/Factory.cpp
- CASAL2/source/Partition/Partition.cpp
- CASAL2/source/Processes/Age/MortalityInstantaneous.cpp (and .h)

@Craig44 - You might just want to double check the changes here:
https://github.com/NIWAFisheriesModelling/CASAL2/compare/master...Craig44:Discards#diff-b4287009e3e9fa0d453ee5d309d7200a

Some of them (e.g. commenting out of CASAL2/source/Selectivities/Common/Logistic.cpp) look like you meant them, so you might not want to lose everything.

**Comment by doonanij** [comment]
Hi Samik
I found that length_bins command for removals_at_length should be in @model in the master, but in Discard branch, the length_bin command is still in the @observation still.
So Craigs branch is not what is in master

Ian

**Comment by Craig44** [comment]
@SamikDatta once you close this issue ill delete my branch
