### ISSUE TITLE
TODO open querying a potential memory leak

### ISSUE THREAD

**Issue by Craig44** [NIWAFisheriesModelling/CASAL2#130]
at line: 487

in Categories/Categories.cpp

there is a query of a memory leak. is this comment okay delete @Zaita

**Comment by Craig44** [comment]
Whilst looking at TODO commands there is also one at line : 223 in Model/Objects.cpp. That I am not sure if needs to be addressed

**Comment by Zaita** [comment]
Fixed The categories one. The 223 in Model/Objects isn't actually needed. I'd delete that and refactor the FindObject and FindEstimable methods to not have that parameter. Would you like me to do it?

Note: This was likely in there because of the SharedLibrary code but I'm assuming I didn't end up needing it with my final implementation.
