### ISSUE TITLE
Projections and time varying for string maps

### ISSUE THREAD

**Issue by Craig44** [NIWAFisheriesModelling/CASAL2#163]
Currently we only all allow unsigned maps to be projected or time_varied but parameters such as M which are string maps we want to extend the functionality to these parameters.

**Comment by Craig44** [comment]
Attached is a model that has the time_varying natural mortality its defined at the top of population.csl2

[Time-varying_natural_mortality.zip](https://github.com/NIWAFisheriesModelling/CASAL2/files/477913/Time-varying_natural_mortality.zip)

**Comment by Zaita** [comment]
Time varying works on Time, so the vector, unsigned map and single value can all be tied to a time. If you want to do a string map it's not going to work because it's arbitrary. There is no way for the projection or time_varying to know how to distribute the changes across the values.

Your best bet is to reference them singularly. 

Otherwise, we have to re-think how Projects and time_varying are done.

**Comment by Zaita** [comment]
Fixed. Reference singularly should work fine.
