### ISSUE TITLE
Check hessian is positive definite

### ISSUE THREAD

**Issue by NIWAFisheriesModelling** [NIWAFisheriesModelling/CASAL2#166]
After each -e run we should check, for the minimisers that generate a hessian if it is positive definite. this is done in ADMB and I think we should add this functionality as well

**Comment by Craig44** [comment]
Since we require to do a Cholesky Decomposition of the covariance which by definition is symetric and has positive diagonals. If we can complete the Cholesky decomposition then the matrix must be positive-definite. following http://math.stackexchange.com/questions/462682/why-does-the-cholesky-decomposition-requires-a-positive-definite-matrix.
