### ISSUE TITLE
Potential issue for working with Casal2 on OneDrive

### ISSUE THREAD

**Issue by Craig44** [NIWAFisheriesModelling/CASAL2#213]
Hey something that i am noticing on my personal computer but none of the servers or other machines I run Casal2 on is. When doing an MCMC I get errors at Reports.cpp line 214 "unable to open file mcmc_samples.out". My initial thought is that this is related to OneDrive as it is the only difference in the working environments. What needs to be looked at is, if Casal2 skips printing these draws and so causes a mis-match between the samples and objectives files. That would be an issue that would need to be resolved.

**Comment by Zaita** [comment]
This will be because OneDrive/GoogleDrive/DropBox etc is locking the file preventing Casal2 from opening it. Same issue can occur with Anti-virus. Casal2 works very quickly and it doesn't like other applications locking the files it's using.

If you want to run Casal2, please ensure folders that do synchronization are not getting high-speed output files.

**Comment by Craig44** [comment]
This is just a note for NIWA users who will (should) have all their working environements on OneDrive,  I am closing this issue now
