### ISSUE TITLE
Discuss update third party libraries

### ISSUE THREAD

**Issue by Zaita** [NIWAFisheriesModelling/CASAL2#227]
Third party libraries (e.g. CppAD) have not been updated since 2014. These should be updated to improve performance and remove bugs.

**Comment by Zaita** [comment]
Google Test has been done.

**Comment by Zaita** [comment]
Moving away from v1.0 as there are no current issues with the versions we have,

**Comment by largek** [comment]
Notes from March 2020 (GitLab issue #45):

The version of BetaDiff in Casal2 is dated 2011. The version in CASAL is dated 2015. Should BetaDiff in Casal2 be updated to match CASAL?

Note, this is an internal-to-NIWA library.

Also note, BetaDiff was created within CASAL, so it was not OSS. In Casal2 it has been OSS since 2015.

Current external third-party libraries:
* ADOL-C 2.5.2
* Boost 1.58
* CppAD 20141128
* DLib 18.16
* Google Test 1.8.1 and Google Mock 
* Parser 1.1

Most recent versions available:
* ADOL-C 2.7.2
* Boost 1.72
* CppAD 20200000.2
* DLib 19.19
* Google Test ? and Google Mock 
* Parser 1.1
