### ISSUE TITLE
Outputting partitions as matrices

### ISSUE THREAD

**Issue by mkienzle** [NIWAFisheriesModelling/CASAL2#241]
Dear all,

several weeks ago a pull request for a new reporting format which provide information about the partitions as 2D matrices (years x age-groups) was merged into the master branch. This format which I refer to as the CEFAS format after the name of the research center in the UK which developed a standard output format for software implementing VPA based methods (ICA, XSA, etc...) needs several improvements, such as:

- clean the code
- display the partition the data belong to
- extend the idea to weight at age
- check the behavior of this method with models containing multiple partitions

Is everyone happy with such output? Any suggestions?

**Comment by smormede** [comment]
Hello,

The Casal2 format gives a matrix of categories x age-groups for each year. Basically we have a 3 dimension problem that wants to be sliced multiple ways. Does this reporting format have a category request for the output (e.g. category immature)? If it does, can it do the addition of categories (e.g. category males + females) , and if not, it should be added because it will likely break for multiple categories. Also probably a good idea to test it on more complex models to make sure it doesn't break other stuff we haven't thought of. Also it probably needs a test that this category is either a single value or multiple values with a + between them. Hopefully all this is already done.
