### ISSUE TITLE
Review: casal_initialisation switch maybe unnecessary and superfluous (please check) (Gitlab issue #33)

### ISSUE THREAD

**Issue by largek** [NIWAFisheriesModelling/CASAL2#338]
This switch should not be in Casal2. I think I added it thinking it was necessary but after further looking in CASAL code it is not in CASAL so should not be a switch or even available in Casal2.

Screenprint: [Review_ casal_initialisation switch maybe unnecessary and superfluous (please check) (#33) · Issues · Fisheries _ modelling _ Casal2 Development · GitLab.pdf](https://github.com/NIWAFisheriesModelling/CASAL2/files/5773401/Review_.casal_initialisation.switch.maybe.unnecessary.and.superfluous.please.check.33.Issues.Fisheries._.modelling._.Casal2.Development.GitLab.pdf)

**Comment by Craig44** [comment]
I believe I know why this line was added into Casal2. Early comparison tests between Casal2 and CASAL were based on an R0 initialised model. There was a discrepancy which was due to CASAL code line:222 (population_section.cpp). This was not picked up, and the difference was thought to be because B0 CASAL models run an extra equilibrium year line:275 (population_section.cpp). I think this switch was added to deal with this discrepency in CASAL B0 / R0 initialisation. My recommendation is to remove the switch from Casal2 to remove confusion. If a difference arises, between CASAL and Casal2 in the equilibrium age-structure we recommend running Casal2 with the iterative initialisation phase for 1000 years, as this will derive the true equilibrium the brute force way.
